<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promises in JS</title>
    <style>
        body{
            background-color: black;
            color: white;
        }
    </style>
</head>
<body>
    <h1> Hello...... </h1>
    <button id="resolve-btn" > Resolve Promise </button>
    <button id="reject-btn" > Reject Promise </button>
</body>
</html>

<script>/* 
    Promises: - It is a solution of callback hell.
              - These are used to remove problem of callback hells.
              - Promise is for "eventual" completion of task. It is an object in JS.

              - Syntax:
                        let promise = new Promise(resolve, reject) => {......}

              - resolve and reject are callbacks provided by JS

              - There can be 3 states of promise:
                    a) Pending : Intial state, neither fulfilled nor rejected. The result is undefined
                    b) Fulfilled (resolved) : Meaning that the operation was completed successfully the result is a value (fulfilled)
                    c) Rejected : meaning that the operation failed. The result is an error object
*/

// Pending
let promise1 = new Promise((resolve, reject) => {
    console.log("I am a Promise");
})

// Resolved
let promise2 = new Promise((resolve, reject) => {
    console.log("I am a Promise");
    resolve("Success")
})

// Rejected
let promise3 = new Promise((resolve, reject) => {
    console.log("I am a Promise");
    reject("Error")
})


// Example question of Promise: Resolving promise after 5 sec.

// creating promise
const p = new Promise((resolve, reject) => {
    setTimeout(() => {
        let error = false
        if(!error){
            resolve({username: "Prashant", email: "email2prashantkr@gmail.com"})
        }
        else {
            reject('ERROR: Something went wrong')
        }
    }, 4000)
})

// consuming promise
p.then((user) => {
    console.log(user);
    return user.username
}).then((username) => {
    console.log(username);
}).catch((error) => {
    console.log(error);
}).finally(() => {
    console.log("The promise is either resolved or rejected");
})


// Button to resolve Promise

const resolveBtn = document.querySelector('#resolve-btn')
const rejectBtn = document.querySelector('#reject-btn')


const promise = new Promise((resolve, reject) => {
    resolveBtn.addEventListener('click', () => {
        resolve('Promise is Resolved')
    })
    rejectBtn.addEventListener('click', () => {
        reject('Promise is Rejected')
    })
})

promise.then((value) => {                        // .then() : triggers when promise is resolved
    console.log(value);                          // Printing value in the resolving code.
}).catch((error) => {                            // .catch() : triggers when promise is rejected                     
    console.log(error);                          // Printing value in the rejecting code.
}).finally(() => {                               // finally calls even the promise is resolved or rejected
    console.log('Finally');
})




// Lets see how Promises helps us to get rid of callback hell

function getCheese(){
    return new Promise((resolve,reject) => {
        setTimeout(() => {
            const cheese = "🧀"
            resolve(cheese)
        }, 6000)
    })
}

function makeDough(cheese){
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            const dough = cheese + "🫓"
            resolve(dough)
        }, 2000)
    })
}


function bakePizza(dough){
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            const pizza = dough + "🍕"
            resolve(pizza)
        }, 2000)
    })
}

// ----------CONSUMING PROMISE BY USING THEN(), CATCH(), FINALLY()---------

// getCheese()
//     .then((cheese) => {
//         console.log("Here is the cheese", cheese);
//         return makeDough(cheese)
//     })
//     .then((dough) => {
//         console.log("Here is the dough", dough);
//         return bakePizza()
//     })
//     .then((pizza) => {
//         console.log("Pizza is ready");
//     })
//     .catch((data) =>{
//         console.log("error occured", data);
//     })
//     .finally(() => {
//         console.log("Process ended");
//     })


// Here, no nesting is taking place. All then, catch and finally are at the same level, which eliminates callback hell



// ----------CONSUMING PROMISE BY USING ASYNC AWAIT---------

/*
 async await: 
    - They are built on top of JavaScript Promises, providing a syntax that looks synchronous but handles asynchronous operations. 
    - They are used to work with asynchronous code in a more readable and manageable way.
    - Always returns a promise
    - async and await are used to handle promises.
    - await can only be used inside the async function.
*/

async function orderPizza() {                           // async keyword is used with functions 
    try{                                                // try and catch is being using to catch the error

        // await keyword here will pause the execution of its surrounding async function until the promise is settled.
        const cheese = await getCheese()                //JS Engine will wait for getCheese(), then will go to next line.
        console.log("here is the cheese", cheese);
        const dough = await makeDough(cheese)
        console.log("here is the dough", dough);
        const pizza = await bakePizza(dough)
        console.log("Here is the Pizza...!", pizza);
    } 
    catch(err){
        console.log("Error occured", err);
    }
    finally {
        console.log("Process ended");
    }
}

orderPizza()

// This async await will take a function call to execute
// If we want to execute the function one time without even calling
// we can use IIFE function like given below:1

/*
(async function () {                           
    try{                                                
        const cheese = await getCheese()               
        console.log("here is the cheese", cheese);
        const dough = await makeDough(cheese)
        console.log("here is the dough", dough);
        const pizza = await bakePizza(dough)
        console.log("Here is the Pizza...!", pizza);
    } 
    catch(err){
        console.log("Error occured", err);
    }
    finally {
        console.log("Process ended");
    }
}) ();

*/




</script>